### ISSUE TITLE
cant find module 'fs', etc

### ISSUE THREAD

**Issue by zhangwuyang-github** [AbhyudayaSharma/react-git-info#27] opened 2022-08-26 08:36 UTC
![image](https://user-images.githubusercontent.com/82797771/186860201-8f373c3c-8297-465a-8e82-bfc9786bb623.png)
![image](https://user-images.githubusercontent.com/82797771/186860243-d103160d-df38-44ca-80ef-d4b0b2153791.png)

**Comment by AbhyudayaSharma** [comment] 2022-08-26 15:29
Are you using create-react-app?

**Comment by AbhyudayaSharma** [comment] 2022-08-27 01:00
Looks like a duplicate of #16. Please reopen if your issue is different.

**Closed as not planned by AbhyudayaSharma** 2022-08-27 01:00 UTC
Labels: bug, duplicate, invalid

**Comment by hugocalheira** [comment] 2023-06-07 01:20
Same error here.
Using Nextjs 13.

![image](https://github.com/AbhyudayaSharma/react-git-info/assets/6580989/2cc6eff6-70eb-4e03-a53f-a527b57d63c7)
![image](https://github.com/AbhyudayaSharma/react-git-info/assets/6580989/955f9f43-dcbc-4e6f-b6d5-ca1f10773260)
